### ISSUE TITLE
storj-up create user with older creation date

### ISSUE THREAD

**Issue by littleskunk** [storj/up#35]
For invoice generation we insert fake usage into the database. The problem we insert with an old timestampe in order to be able to create the invoice for the previous month like we would in production. This only works if we manipulate the creation date of the user. It would be great it storj-up could create the user with an timestamp 90 days back. That would give us enough room to insert fake data. 

storj-up credentials --email alice@mail.test 
https://github.com/storj/up/blob/23e2923cc3d95ff54142c65eaa201d76910ad8af/pkg/console.go#L102

**Comment by mobyvb** [comment]
Actually, the creation date on the user in the `users` table is not an issue. The problem is the creation date on the `stripe_customers` row, after the user logs in for the first time. There are some manual database queries we can run to override the created_at timestamp, so perhaps we could add a simple command like `storj-up override-stripe-customer-created-at` which runs a query in the DB to set created_at to a year ago for anything in `stripe_customers`.

Even better if we could insert the user with a custom timestamp, but I think this would be more involved and would require some changes in storj/storj for it to be possible. I think a hacky solution would be okay for now.

**Comment by nadimhq** [comment]
https://github.com/storj/up/pull/34/files#diff-433af5f0ce3e92d77a3b5ec45b05701a533197a4f2132fec267b4919a923b1f8

Added this command --> **storj-up testdata fix-billing**, should be ran after **storj-up credentials** _and logging in with said alice account_
also if invoice steps are followed without credit card it should be no problem as the invoice is still visible on stripe and in the billing history UI

**Comment by dlamarmorgan** [comment]
When I try running this command and generating the invoice, I get the errors

```
2022-08-23T23:28:48.597Z        INFO    process/exec_conf.go:313        Invalid configuration file value for key       {"Key": "overlay.node.upload-excluded-country-codes"}
2022-08-23T23:28:48.597Z        INFO    process/exec_conf.go:313        Invalid configuration file value for key       {"Key": "overlay.repair-excluded-country-codes"}
2022-08-23T23:28:48.597Z        INFO    process/exec_conf.go:313        Invalid configuration file value for key       {"Key": "overlay.geo-ip.mock-countries"}
```

Are there extra ENV variables that need to be set in the compose file for invoice generation to work correctly?

**Comment by littleskunk** [comment]
Let's continue our conversation in https://github.com/storj/up/pull/34
